### ISSUE TITLE
Show app icons on all apps page

### ISSUE THREAD

**Issue by stevennyman** [MehediH/winstall#3]
Would it possible to show app icons on the all apps page? The logos would make it easier to skim the page.

**Comment by d3ward** [comment]
@MehediH You could use a service to retrieve favicons from a url like [besticon](https://github.com/mat/besticon)

**Comment by MehediH** [comment]
@d3ward yeah, but the problem is that the app doesn’t have the homepage URL for the individual apps till they are loaded into the local cache, so it would only show the favicons when a user loads the details of an app. I feel like that would result in a weird interface where some apps have icons and others don’t.

**Comment by d3ward** [comment]
You're right. It can be particularly annoying. I think the solution gets more and more complicated. Maybe a file ( name - url ) with all the packages could simplify the process but is still not productive enough .

**Comment by MehediH** [comment]
This has been added with the new release. Winstall will attempt to show a favicon where possible, and if not there will be a placeholder.
