### ISSUE TITLE
Script should be a .ps1, not .bat

### ISSUE THREAD

**Issue by Benjin** [MehediH/winstall#7]
Powershell's been the defacto scripting language for Windows since 2007.  No reason anyone should be writing .bat scripts anymore.

**Comment by MehediH** [comment]
The reason I decided to go with .bat was because it was much more accessible to install. I believe .ps1 scripts require you to change some permissions. Anyway, I have added the option to generate .ps1 scripts:

![image](https://user-images.githubusercontent.com/10274434/82699776-2be0bc80-9c65-11ea-83ff-e510ddefe712.png)

**Comment by Benjin** [comment]
Awesome, thanks!  Copy-pasting into powershell will work just fine without any permission changes.

**Comment by IanYates** [comment]
> Awesome, thanks! Copy-pasting into powershell will work just fine without any permission changes.

I think @MehediH was worried about people downloading a PS1 script and then expecting to double-click it.  Permissions in that case can be an issue depending on how PowerShell is configured.

It's nice to have both options available :)
